# Generated by Django 5.2.4 on 2025-07-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=100)),
                ('t_type', models.CharField(choices=[('mm', 'Пакет минут'), ('que', 'Пакет запросов'), ('mon', 'Подписка на месяц')], max_length=20)),
                ('t_quatity', models.IntegerField()),
                ('t_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_date', models.DateTimeField(auto_now_add=True)),
                ('t_name', models.CharField(max_length=100)),
                ('t_type', models.CharField(max_length=20)),
                ('t_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('s_status', models.BooleanField(default=False)),
                ('s_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('t_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_session_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarifLog',
            fields=[
                ('tl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tl_date', models.DateTimeField(auto_now_add=True)),
                ('t_name', models.CharField(max_length=100)),
                ('t_type', models.CharField(max_length=20)),
                ('t_quatity', models.IntegerField()),
                ('tl_status', models.BooleanField(default=False)),
                ('tl_status_pay', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_tarif_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
