# Generated by Django 5.2.4 on 2025-07-19 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(default='Новая сессия', max_length=255)),
                ('c_created', models.DateTimeField(auto_now_add=True)),
                ('c_date', models.DateTimeField()),
                ('c_closed', models.BooleanField(default=False)),
                ('is_free_session', models.BooleanField(default=False)),
                ('free_limit_reached', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'ИИ')], max_length=10)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
