# Generated by Django 5.2.4 on 2025-07-19 18:01
import django
from django.db import migrations
from django.db import models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        # Автоматически пересоздаст таблицу при применении миграции
        migrations.CreateModel(
            # Здесь должно быть определение модели (скопируйте из models.py)
            name='Chat',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(default='Новая сессия', max_length=255)),
                ('c_created', models.DateTimeField(auto_now_add=True)),
                ('c_date', models.DateTimeField()),
                ('c_closed', models.BooleanField(default=False)),
                ('is_free_session', models.BooleanField(default=False)),
                ('free_limit_reached', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_chat',  to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
