# Generated by Django 5.2.4 on 2025-07-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('s_status', models.BooleanField(default=False)),
                ('s_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('t_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('messages_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_session_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
