# Generated by Django 5.2.4 on 2025-07-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgTest',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_state', models.CharField(max_length=100)),
                ('i_comment', models.CharField(max_length=500)),
                ('i_image', models.ImageField(upload_to='analysis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
