# Generated by Django 5.2.4 on 2025-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgtest',
            name='i_image',
        ),
        migrations.AddField(
            model_name='imgtest',
            name='i_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
